In [14]:
import numpy as np

In [13]:
np.empty(2)

array([4.67877148e-310, 0.00000000e+000])

In [12]:
arr = np.ones(2, dtype=np.int64)
arr

array([1, 1])

In [11]:
arr_3d = np.array([[[0, 1, 2, 3],
                    [4, 5, 6, 7]],

                   [[0, 1, 2, 3],
                    [4, 5, 6, 7]],

                   [[0, 1, 2, 3],
                    [4, 5, 6, 7]]])

In [15]:
arr_3d.ndim

3

In [16]:
arr_3d.size

24

In [17]:
arr_3d.shape

(3, 2, 4)

In [18]:
np.arange(2,9,2)

array([2, 4, 6, 8])

In [19]:
arr = np.arange(6)
print(arr)

[0 1 2 3 4 5]


In [20]:
new_arr = arr.reshape(3,2)
print(new_arr)

[[0 1]
 [2 3]
 [4 5]]


In [21]:
arr = np.array([[0,1],[2,3]])

In [22]:
np.resize(arr,(2,3))

array([[0, 1, 2],
       [3, 0, 1]])

In [23]:
arr = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
arr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])